### ISSUE TITLE
Syndicator error  created by [Pet cage] item in Guild Bank

### ISSUE THREAD

**Issue by JunkHead1979** [Baganator/Syndicator#50] opened 2024-09-23 22:54 UTC
### What version(s) of WoW are you using?

Retail

### What version of Syndicator?

Syndicator-124

### What isn't working? What was supposed to happen?

Lua error created when opening guild bank which had an item, [Pet Cage] on tab 1. Item has red text, "This was never available to players." Removing the item from the guild bank stopped error from occurring. Below I will paste error.

### Are you experiencing any lua errors

Message: Interface/AddOns/Syndicator/Tracking/Utilities.lua:51: attempt to concatenate field '?' (a nil value)
Time: Mon Sep 23 17:14:09 2024
Count: 6
Stack: Interface/AddOns/Syndicator/Tracking/Utilities.lua:51: attempt to concatenate field '?' (a nil value)
[string "@Interface/AddOns/Syndicator/Tracking/Utilities.lua"]:51: in function `RecoverBattlePetLink'
[string "@Interface/AddOns/Syndicator/Tracking/GuildCache.lua"]:295: in function `DoSlot'
[string "@Interface/AddOns/Syndicator/Tracking/GuildCache.lua"]:314: in function `ExamineBankTab'
[string "@Interface/AddOns/Syndicator/Tracking/GuildCache.lua"]:243: in function `ExamineAllBankTabs'
[string "@Interface/AddOns/Syndicator/Tracking/GuildCache.lua"]:164: in function <Interface/AddOns/Syndicator/Tracking/GuildCache.lua:162>

Locals: tooltipInfo = <table> {
 dataInstanceID = 8078
 type = 0
 isAzeriteEmpoweredItem = false
 isAzeriteItem = false
 id = 82800
 hyperlink = "[Pet Cage]"
 isCorruptedItem = false
 lines = <table> {
 }
}
itemString = "battlepet"
(for state) = <table> {
 1 = "battlePetSpeciesID"
 2 = "battlePetLevel"
 3 = "battlePetBreedQuality"
 4 = "battlePetMaxHealth"
 5 = "battlePetPower"
 6 = "battlePetSpeed"
}
(for control) = 1
_ = 1
key = "battlePetSpeciesID"
(*temporary) = "battlepet"
(*temporary) = ":"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate field '?' (a nil value)"
battlePetTooltip = <table> {
 1 = "battlePetSpeciesID"
 2 = "battlePetLevel"
 3 = "battlePetBreedQuality"
 4 = "battlePetMaxHealth"
 5 = "battlePetPower"
 6 = "battlePetSpeed"
}

**Comment by zeenk** [comment] 2024-09-23 23:11
Did you recently transfer faction or realm or is that "pet" part of the items you got back from the broken guild banks?
https://www.wowhead.com/item=82800/pet-cage#comments

Reading some wowhead comments about it and people seem to get this if the pet gets broken and is no longer useable or something 🤔

**Comment by JunkHead1979** [comment] 2024-09-23 23:19
Nope! I just recently came back to the game after having not really played since Legion. This item has been in the guild bank for years. Now, I do remember many years ago, I did have to do a guild bank restore from a hack attempt. It occurred in October 2013 according to my email. Could that be the issue?

**Comment by zeenk** [comment] 2024-09-23 23:27
That could be the cause as the restored item wasn't able to be fully restored, so that pet you had might be gone forever (But keep it for now if plusmouse, the Baganator dev) needs to do some testing to avoid this issue in the future.

**Comment by JunkHead1979** [comment] 2024-09-23 23:29
Yeah np. I moved it to my normal bank and there is no error. So perhaps it was isolated to gbank only. But yeah i still have it. I will also sow a screenshot just to add more info.
![WoWScrnShot_092324_173235](https://github.com/user-attachments/assets/b985b62f-bd23-4254-bd84-a8c617ec1b21)

**Comment by JunkHead1979** [comment] 2024-09-23 23:33
Also adding more info. And this is complicated to type, so hopefully it makes sense. With Baganator/syndicator both enabled, in addition to the lua error I pasted above, the guild bank also looked different. Tab 1 was completely empty except for one item in the top left most slot. changing to another tab, say tab 2, then BACK to tab 1, now showed tab 1 as having items, but it was the items from the previous tab you viewed. If that makes any sense.

**Comment by plusmouse** [comment] 2024-09-23 23:37
That would make sense, the scan failed because of the broke pet cage. so one tab wouldn't refresh properly.

**Comment by plusmouse** [comment] 2024-09-23 23:38
I'll add some shielding code tomorrow to ensure that if this happens again it'll just be missing the pet icon, and not break the guild bank entirely.

**Comment by JunkHead1979** [comment] 2024-09-23 23:39
This is probably not something that will occur often but I'm glad I could help nonetheless. :)

**Comment by plusmouse** [comment] 2024-11-15 20:22
Update: Going to close this issue as I've added the shielding code now.

**Closed by plusmouse** 2024-11-15 20:22 UTC
Labels: bug, retail
